services:
  postgres:
    image: postgres:16-alpine
    container_name: tehtrak-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tehtrak
      POSTGRES_PASSWORD: tehtrak
      POSTGRES_DB: tehtrak
    volumes:
      - tehtrak_pg_data:/var/lib/postgresql/data

volumes:
  tehtrak_pg_data:
